<ReviewScreen>
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            id:review
            orientation: 'horizontal'
            size_hint:(1.5, 5)
            BoxLayout:
                id: patient_records
                orientation: 'vertical'
        Button:
            text: 'Go Back'
            color: (1,0,0,1)
            on_press: app.login_in()
        Label:
            text:app.verification
            color : (0,0,.75,1)











